### ISSUE TITLE
JAR file validation fails

### ISSUE THREAD

**Issue by sormuras** [HanSolo/jdktools#1]
Hi Gerrit,

Running `jar --validate --file jdktools-17.0.4.jar` using `jdk` of JDK 17 (17.0.1, 17.0.2), 18 RC, and 19-ea yields:

```
java.lang.UnsupportedOperationException: This feature requires ASM9_EXPERIMENTAL
        at java.base/jdk.internal.org.objectweb.asm.ClassVisitor.visitPermittedSubclassExperimental(ClassVisitor.java:299)
        at java.base/jdk.internal.org.objectweb.asm.ClassReader.accept(ClassReader.java:715)
        at java.base/jdk.internal.org.objectweb.asm.ClassReader.accept(ClassReader.java:432)
        at jdk.jartool/sun.tools.jar.FingerPrint.getClassAttributes(FingerPrint.java:165)
        at jdk.jartool/sun.tools.jar.FingerPrint.<init>(FingerPrint.java:81)
        at jdk.jartool/sun.tools.jar.Validator.getFingerPrint(Validator.java:142)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.zip.ZipFile$EntrySpliterator.tryAdvance(ZipFile.java:558)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at jdk.jartool/sun.tools.jar.Validator.validate(Validator.java:83)
        at jdk.jartool/sun.tools.jar.Validator.validate(Validator.java:74)
        at jdk.jartool/sun.tools.jar.Main.validateJar(Main.java:446)
        at jdk.jartool/sun.tools.jar.Main.run(Main.java:424)
        at jdk.jartool/sun.tools.jar.Main.main(Main.java:1698)
```

I am not sure what the underlying issue is.

It seems to related to experimental/preview features of ASM. Does `jdktools` use incubating and/or preview features?

**Comment by aalmiray** [comment]
Did the following steps:
- upgraded the build to Gradle wrapper 7.4
- removed the modularity plugin, use Gradle's JPMS support
- apply the `application` plugin
- removed the `beryx.jlink` plugin
- upgraded bnd plugin to 6.2.0

Same error. However if the bnd plugin is commented out I get a different error

```
$ jar --validate --file build/libs/jdktools-17.0.4.jar 
java.lang.UnsupportedOperationException: This feature requires ASM8
```

**Comment by HanSolo** [comment]
@sormuras Nope, it should only be released features...no experimental so far...at least that's the settings in Intellij, so I guess it would also complain if there would be experimental features used. I also cleaned it up a bit, still contained unused stuff.

**Comment by HanSolo** [comment]
I've created a complete new project and only copied the .java files using no gradle plugins at all...and it leads to the same error "This feature requires ASM8". Also replace the one record that I use by a class did not fix it, so at the moment I have no idea why it fails...

**Comment by sormuras** [comment]
Tried the following steps with the source from this project:

- `javac --module eu.hansolo.jdktools --module-source-path eu.hansolo.jdktools=src\main\java -d out/classes`
- `jar --create --file out/eu.hansolo.jdktools.jar -C out/classes/eu.hansolo.jdktools .`
- `jar --validate --file out/eu.hansolo.jdktools.jar`

And it also produces:

```
 java.lang.UnsupportedOperationException: This feature requires ASM9_EXPERIMENTAL
        at java.base/jdk.internal.org.objectweb.asm.ClassVisitor.visitPermittedSubclassExperimental(ClassVisitor.java:299)
        at java.base/jdk.internal.org.objectweb.asm.ClassReader.accept(ClassReader.java:715)
        at java.base/jdk.internal.org.objectweb.asm.ClassReader.accept(ClassReader.java:432)
        at jdk.jartool/sun.tools.jar.FingerPrint.getClassAttributes(FingerPrint.java:165)
        at jdk.jartool/sun.tools.jar.FingerPrint.<init>(FingerPrint.java:81)
        at jdk.jartool/sun.tools.jar.Validator.getFingerPrint(Validator.java:142)
```

Something's off here... 🤔

**Comment by HanSolo** [comment]
Took the jdk11 branch and did the same...and it works...

**Comment by sormuras** [comment]
_"Getting closer..."_

**Comment by HanSolo** [comment]
I think I have something...I've compiled the jdk11 branch with Zulu 11 and it works...then I compiled the jdk11 branch with Zulu 17 and it fails...

**Comment by HanSolo** [comment]
Will now try with Temurin 17.0.2...

**Comment by HanSolo** [comment]
Same thing...with Temurin 17.0.2 and the main branch it also fails...

**Comment by aalmiray** [comment]
This might be a change in later JDKs a it works on 11

**Comment by HanSolo** [comment]
I will now give 16.0.2 a try...

**Comment by sormuras** [comment]
Created https://bugs.openjdk.java.net/browse/JDK-8282446 to track this JDK-related issue.

**Comment by HanSolo** [comment]
16.0.2 also fails...

**Comment by aalmiray** [comment]
Removing all JDK17 syntax makes `jar --validate` work. It's one of:
- record
- switch expression
- Stream.toList()

**Comment by HanSolo** [comment]
Yep I've already tried to remove record and Stream.toList() so it seems to be the switch...will try...

**Comment by HanSolo** [comment]
And I guess the comma separated case statements are the problem...

**Comment by sormuras** [comment]
It's all of those not covered by `Opcodes.ASM7`: https://github.com/openjdk/jdk/blob/master/src/jdk.jartool/share/classes/sun/tools/jar/FingerPrint.java#L246-L248
